# Generated by Django 2.1.15 on 2020-06-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='moviesrc',
            field=models.CharField(max_length=500),
        ),
    ]
