# Generated by Django 2.1.15 on 2020-06-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='backdrop_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.TextField(),
        ),
    ]
